[package]
name = "warp"
version = "0.1.0"
authors = ["piaoger"]
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
serde = { version = "1.0", features = ["derive"] }